AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy EC2 Fleet'

#Build AWs resources
Resources:
  #Create a EC2 Launch template
  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        ImageId: ami-0d6621c01e8c2de2c
        TagSpecifications:
          - ResourceType : instance
            Tags: 
              - Key: Name
                Value: ec2-fleet
          - ResourceType : volume
            Tags: 
              - Key: Name
                Value: ec2-fleet                
  
  EC2Fleet:
    Type: AWS::EC2::EC2Fleet
    Properties: 
      ExcessCapacityTerminationPolicy: termination
      LaunchTemplateConfigs: 
        - LaunchTemplateSpecification:
            LaunchTemplateId: !Ref EC2LaunchTemplate
            Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
          Overrides:
            - InstanceType: m5.large
              Priority: 20
            - InstanceType: r5.large
              Priority: 50
      OnDemandOptions: 
        AllocationStrategy: prioritized
      ReplaceUnhealthyInstances: true
      SpotOptions: 
        AllocationStrategy: lowestPrice
      TagSpecifications: 
        - ResourceType : fleet
          Tags: 
            - Key: project
              Value: ec2-fleet
      TargetCapacitySpecification: 
        DefaultTargetCapacityType: spot
        OnDemandTargetCapacity: 1
        SpotTargetCapacity: 2
        TotalTargetCapacity: 3
      TerminateInstancesWithExpiration: true
      Type: maintain

# Output
Outputs:
  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'