#!/bin/sh

set -euo pipefail

# extract the CLI commands to work around the 250 MB hard limit
if [ -f "/opt/cli.tar.gz" ]; then 
  echo "Extracting list of cli commands"
  mkdir -p /tmp/cli; tar xzf /opt/cli.tar.gz -C /tmp/cli
fi

export PATH=$PATH:/opt/awscli:/opt/kubectl:/tmp/cli

# Processing
while true
do
  HEADERS="$(mktemp)"
  # Get an event
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Execute the handler function from the script
  RESPONSE=$(./$(echo "$_HANDLER" | cut -d. -f2).sh "$EVENT_DATA")


  echo "=========[RESPONSE]======="
  echo "$RESPONSE"
  echo "=========[/RESPONSE]======="

  # Send the response
  curl -s -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "$RESPONSE"
done
